// ─────────────────────────────────────────────
// COMMAND CENTRAL — CONFIG
// Only edit this file. Everything else is automatic.
// ─────────────────────────────────────────────
const CONFIG = {
  GOOGLE_CLIENT_ID: '356573367790-5u6o8jhf3sporr6t0mp585dff7i4ral6.apps.googleusercontent.com',
  YOUR_NAME: 'Austin',
  EMAIL_COUNT: 10,
  EVENT_DAYS_AHEAD: 7,
  DRIVE_FILES_COUNT: 8,
  // Local status.json path — generated by a cron job at the repo root.
  STATUS_JSON: 'status.json',
  // Weather (wttr.in, no key needed)
  WEATHER_LOCATION: 'Pennsylvania',
  // Quick-launch links (sidebar + dashboard)
  QUICK_LINKS: [
    { label: 'Shopify Admin', url: 'https://bq0xey-rg.myshopify.com/admin', icon: 'S' },
    { label: 'PawZen Store', url: 'https://pawzenvibes.com', icon: 'P' },
    { label: 'n8n Workflows', url: 'http://192.168.1.246:5678', icon: 'N' },
    { label: 'GitHub', url: 'https://github.com/mackeyaustin18-afk', icon: 'G' },
    { label: 'OpenClaw Docs', url: 'https://docs.openclaw.ai', icon: 'O' },
  ],
  // Deprecated — Railway sync API is dead. status.json replaces it.
  // SYNC_API: '',
};
